# Generated by Django 2.0.1 on 2018-01-28 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
