# Generated by Django 2.0.1 on 2018-01-28 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180128_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=14, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
